import os
import re
import asyncio
from dotenv import load_dotenv
from transformers import pipeline
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage

load_dotenv()

# ─── Step 1: Strip dialogue labels ───
def clean_transcript(text: str) -> str:
    """Remove speaker labels like 'Person 1:', 'Interviewer:', 'Candidate:' etc.
    Returns only the raw spoken words."""
    # Remove lines that are just labels, and strip label prefixes from content lines
    cleaned = re.sub(r'(?i)(person\s*\d+|interviewer|candidate)\s*:\s*', '', text)
    # Collapse multiple newlines into single newlines
    cleaned = re.sub(r'\n{2,}', '\n', cleaned).strip()
    return cleaned


# ─── Step 2: HuggingFace DistilBERT Score ───
def get_hf_score(text: str) -> float:
    """Run the lightweight DistilBERT AI detector locally.
    Returns a 0-100 AI probability score."""
    detector = pipeline(
        "text-classification",
        model="ahmediqbal/ai-text-detector-model"
    )
    result = detector(text)
    label = result[0]['label']
    score = result[0]['score']
    
    # If label is 'AI', the score IS the AI probability
    # If label is 'Human', the AI probability is (1 - score)
    if label.upper() == 'AI':
        ai_prob = score
    else:
        ai_prob = 1.0 - score
    
    return round(ai_prob * 100, 2)


# ─── Step 3: GPT-4o-mini Stylometric Score ───
async def get_llm_score(text: str) -> float:
    """Ask gpt-4o-mini to perform stylometric analysis.
    Returns a 0-100 AI probability score."""
    llm = ChatOpenAI(
        api_key=os.getenv("AIMLAPI_KEY"),
        base_url="https://api.aimlapi.com/v1",
        model="gpt-4o-mini",
        temperature=0.1,
    )

    system_prompt = """You are an AI text detection expert. Analyze the given text and determine the probability it was generated by an AI (like ChatGPT).

Look for:
- Classic LLM vocabulary ("multifaceted", "synergistic", "leverage", "it's important to note")
- Formulaic essay structure in spoken dialogue
- Absence of conversational fillers ("um", "ah", "like", "you know"), pauses, or self-corrections
- Unnaturally perfect grammar and sentence structure for spoken language

Respond with ONLY a single integer between 0 and 100 representing the AI probability percentage. Nothing else. Just the number."""

    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=f"Text to analyze:\n{text}")
    ])

    # Parse the number from the response
    try:
        score = int(re.search(r'\d+', response.content).group())
        return min(max(score, 0), 100)  # Clamp between 0-100
    except:
        return 50.0  # Default to 50 if parsing fails


# ─── Step 4: Combine Scores ───
async def analyze(transcript: str):
    """Run the full dual-detection pipeline."""
    print("=" * 50)
    print("DUAL AI DETECTION PIPELINE")
    print("=" * 50)
    
    # Clean the transcript
    cleaned = clean_transcript(transcript)
    print(f"\nCleaned text:\n{cleaned}\n")
    
    # Get HuggingFace score
    print("Running HuggingFace DistilBERT detector...")
    hf_score = get_hf_score(cleaned)
    print(f"  HuggingFace AI Score: {hf_score}%")
    
    # Get LLM score
    print("Running GPT-4o-mini stylometric analysis...")
    llm_score = await get_llm_score(cleaned)
    print(f"  GPT-4o-mini AI Score: {llm_score}%")
    
    # Weighted average: 40% HuggingFace + 60% LLM (LLM is more reliable on transcripts)
    final_score = round(0.4 * hf_score + 0.6 * llm_score, 1)
    
    print(f"\n{'=' * 50}")
    print(f"FINAL COMBINED AI-PROBABILITY SCORE: {final_score}%")
    print(f"{'=' * 50}")


# ─── Test Cases ───
if __name__ == "__main__":
    # Test Case: Your human-written transcript
    test_human = """
Interviewer: Tell me about yourself.

Candidate: My name is Alex Johnson, and I recently completed my Bachelor's degree in Computer Science. Over the past two years, I have focused on machine learning and backend development. I completed an internship where I built automated reporting pipelines using Python and SQL, which reduced manual work for the operations team. I also enjoy participating in hackathons and building AI-powered applications.

Interviewer: Can you describe a challenging project you worked on?

Candidate: One of the most challenging projects was developing a resume screening system using natural language processing. The main difficulty was handling resumes in different formats, including PDFs and scanned images. I used OCR for text extraction and then applied transformer-based models to identify skills and match candidates to job requirements. The system improved screening efficiency and reduced the time recruiters spent reviewing applications.

Interviewer: How do you handle tight deadlines?

Candidate: I prioritize tasks based on impact and urgency. I break large projects into smaller milestones, communicate progress regularly with stakeholders, and focus on delivering a working solution before adding extra features. This approach has helped me complete several projects successfully under strict deadlines.

Interviewer: Why are you interested in this role?

Candidate: I am excited about this role because it combines software engineering and artificial intelligence, which are the areas I am most passionate about. I believe my experience with machine learning projects and collaborative development will allow me to contribute effectively while continuing to learn from experienced team members.    """

    asyncio.run(analyze(test_human))