import sys
import os
import re
import logging
import asyncio
import requests
from dotenv import load_dotenv

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import InMemorySaver
from thenvoi import Agent
from thenvoi.adapters import LangGraphAdapter
from langchain_core.tools import tool
from langchain_core.messages import SystemMessage, HumanMessage

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ─── Load HuggingFace model once at startup (avoid reloading on every call) ───
# --- LOCAL MODEL (Commented out for Render deployment to save RAM) ---
# logger.info("Loading HuggingFace DistilBERT AI detector model...")
# from transformers import pipeline as hf_pipeline
# hf_detector = hf_pipeline(
#     "text-classification",
#     model="ahmediqbal/ai-text-detector-model"
# )
# logger.info("HuggingFace model loaded successfully!")


# ─── Helper: Strip dialogue labels ───
def clean_transcript(text: str) -> str:
    """Remove speaker labels like 'Person 1:', 'Interviewer:', 'Candidate:' etc."""
    cleaned = re.sub(r'(?i)(person\s*\d+|interviewer|candidate)\s*:\s*', '', text)
    cleaned = re.sub(r'\n{2,}', '\n', cleaned).strip()
    return cleaned


# ─── Helper: Get HuggingFace score ───
def get_hf_score(text: str) -> float:
    """Run the lightweight DistilBERT AI detector. Configured for HF API to save RAM on Render."""
    
    # --- LOCAL INFERENCE (Commented out) ---
    # result = hf_detector(text)
    # label = result[0]['label']
    # score = result[0]['score']
    # if label.upper() == 'AI':
    #     return round(score * 100, 2)
    # else:
    #     return round((1.0 - score) * 100, 2)

    # --- HUGGINGFACE API INFERENCE ---
    try:
        API_URL = "https://api-inference.huggingface.co/models/ahmediqbal/ai-text-detector-model"
        # We assume you added HUGGINGFACE_API_KEY to your .env file
        headers = {"Authorization": f"Bearer {os.getenv('HUGGINGFACE_API_KEY')}"}
        
        response = requests.post(API_URL, headers=headers, json={"inputs": text})
        result = response.json()
        
        # The API returns a list of lists: [[{'label': 'AI', 'score': 0.99}, {'label': 'HUMAN', 'score': 0.01}]]
        if isinstance(result, list) and len(result) > 0 and isinstance(result[0], list):
            predictions = sorted(result[0], key=lambda x: x['score'], reverse=True)
            top_prediction = predictions[0]
            label = top_prediction['label']
            score = top_prediction['score']
            
            if label.upper() == 'AI':
                return round(score * 100, 2)
            else:
                return round((1.0 - score) * 100, 2)
        else:
            logger.error(f"Unexpected API response: {result}")
            return 50.0 # fallback
    except Exception as e:
        logger.error(f"HF API Error: {e}")
        return 50.0 # fallback if API fails


# ─── Tool: Dual AI Detection ───
@tool
async def analyze_transcript_for_plagiarism(transcript: str) -> str:
    """
    Call this tool when you receive a transcript to analyze.
    It runs a dual AI detection pipeline (HuggingFace ML + GPT-4o-mini stylometrics)
    and returns a combined AI-Probability score.
    """
    logger.info("Running Dual AI Detection Pipeline...")

    # Step 1: Clean transcript
    cleaned = clean_transcript(transcript)
    logger.info(f"Cleaned transcript: {cleaned[:200]}...")

    # Step 2: HuggingFace DistilBERT score
    hf_score = get_hf_score(cleaned)
    logger.info(f"HuggingFace AI Score: {hf_score}%")

    # Step 3: GPT-4o-mini stylometric score
    llm = ChatOpenAI(
        api_key=os.getenv("AIMLAPI_KEY"),
        base_url="https://api.aimlapi.com/v1",
        model="gpt-4o-mini",
        temperature=0.1,
    )

    system_prompt = """You are an AI text detection expert. Analyze the given text and determine the probability it was generated by an AI (like ChatGPT).

Look for:
- Classic LLM vocabulary ("multifaceted", "synergistic", "leverage", "it's important to note")
- Formulaic essay structure in spoken dialogue
- Absence of conversational fillers ("um", "ah", "like", "you know"), pauses, or self-corrections
- Unnaturally perfect grammar and sentence structure for spoken language

Respond with ONLY a single integer between 0 and 100 representing the AI probability percentage. Nothing else. Just the number."""

    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=f"Text to analyze:\n{cleaned}")
    ])

    try:
        llm_score = int(re.search(r'\d+', response.content).group())
        llm_score = min(max(llm_score, 0), 100)
    except:
        llm_score = 50

    logger.info(f"GPT-4o-mini AI Score: {llm_score}%")

    # Step 4: Weighted average (40% HF + 60% LLM)
    final_score = round(0.4 * hf_score + 0.6 * llm_score, 1)
    logger.info(f"Final Combined AI-Probability Score: {final_score}%")

    return f"HuggingFace Score: {hf_score}% | GPT-4o-mini Score: {llm_score}% | Final Combined AI-Probability Score: {final_score}%"


async def main():
    load_dotenv()

    agent_id = os.getenv("PLAGIARISM_AGENT_ID")
    api_key = os.getenv("PLAGIARISM_AGENT_KEY")
    
    if not agent_id or not api_key:
        logger.error("Missing PLAGIARISM_AGENT_ID or PLAGIARISM_AGENT_KEY in .env!")
        return

    llm = ChatOpenAI(
        api_key=os.getenv("AIMLAPI_KEY"),
        base_url="https://api.aimlapi.com/v1",
        model="gpt-4o-mini",
        temperature=0.1,
    )

    adapter = LangGraphAdapter(
        llm=llm,
        checkpointer=InMemorySaver(),
        additional_tools=[analyze_transcript_for_plagiarism],
        custom_section="""
          You are PlagiarismAgent, an AI authenticity detector.
          
          PURPOSE:
          You receive interview transcripts and determine if the candidate was using AI-generated answers.
          
          WORKFLOW:
          1. Wait until you receive or are tagged with an interview transcript.
          2. Use the `analyze_transcript_for_plagiarism` tool to run the dual detection pipeline on the transcript.
          3. Read the tool output. It contains three scores: HuggingFace ML score, GPT-4o-mini stylometric score, and the final combined score.
          4. Post ONLY the final combined AI-Probability Score in the chat, and you MUST start your message by tagging @InterviewAgent so it knows to drop the final Report Card. Example: "@InterviewAgent AI-Probability Score: 45%"
          5. Do NOT output any reasoning, markdown reports, or extra text. Just the tag and the final score.
        """
    )

    agent = Agent.create(
        adapter=adapter,
        agent_id=agent_id,
        api_key=api_key,
    )

    logger.info("PlagiarismAgent running.Waiting for transcripts...")
    await agent.run()

if __name__ == "__main__":
    asyncio.run(main())
